### ISSUE TITLE
Add properties 'has charge', 'has atomic number' for atom

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#100]
From COB workshop:
Are we proposing to add properties such as ‘has charge’, has atomic number’ etc.?

**Comment by wdduncan** [comment]
Per COB workshop: Also create logical definitions:

Introduce two new, non-transitive children of has_part: 
- has_proton_part; domain: material, range: proton
- has_atomic_nucleus_part; domain: material, range: atomic_nucleus
- Define atomic_nucleus with has_proton_part min 1
- Define atom with has_atomic_nucleus exactly 1
- Define molecular entity with has_atomic_nucleus min 2

**Comment by wdduncan** [comment]
We've add data properties `has atomic number`, `has number of atomic nuclei`.
We are using data range restrictions. E.g., `'has number of atomic nuclei' some xsd:nonNegativeInteger[> 1] `

**Comment by bpeters42** [comment]
It looks like all of this is now in COB? I think we can close the ticket?
