### ISSUE TITLE
tritiated  thymidine

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#105]
From COB:
How can we best represent tritiated  thymidine CHEBI:53526.

cc @addiehl

**Comment by jamesaoverton** [comment]
See also [OBI:0000669 tritiated thymidine incorporation assay](http://purl.obolibrary.org/obo/OBI_0000669) for context.

**Comment by wdduncan** [comment]
COB comment (Jonathan Bisson):
deuterated compounds can have different activities than the non-deuterated organisms (plants in particular) have different rates of exchanges with hydrogen, deuterium… same with carbon 12 and 13.
also electronically compounds are not the same, their spectra (IR, NMR) are not the same…

"Deutetrabenazine is a deuterated version of tetrabenazine. It was developed by Teva and approved by the FDA in 2017 as a treatment for Huntington's disease; it has a longer half life than the non-deuterated form of tetrabenazine, which had been approved earlier for the same use.[12] " 

(you have other examples here: https://en.wikipedia.org/wiki/Deuterated_drug )

**Comment by cmungall** [comment]
Thanks all for your comments.

I am not sure this represents a case that impacts the upper level classification in COB, but nevertheless we can incorporated this class into cob-examples, and we can see if classification becomes inconsistent with CHEBI

FWIW, some additional comments here for want of a better place to put them.

I note the CHEBI class lacks an inchi key;
https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_53526

I believe there should be, see:
https://www.inchi-trust.org/technical-faq-2/#9.1

If your ontology (e.g. OBI) uses CHEBI classes you may want to check these classes have inchis as this one of the main ways to do chemical identty normalization outside the world of ontologies, and make tickets for those lacking.

CHEBI does not logically define tritiated thymidine, but there is a functional-parent edge between this and thymidine. I think this could easily be done as a logical definition. But this is a matter for CHEBI, someone could make a ticket there.

I am closing this for now as we have the example in cob-examples
