### ISSUE TITLE
Change label of 'successful planned process'

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#109]
Per COB workshop:
change label of 'successful planned process'.
suggestions:

- completed planned process

**Comment by pbuttigieg** [comment]
+1 for completed

In that the process realised both its objective and action specifications

**Comment by jamesaoverton** [comment]
When considering these labels, we want to distinguish at least three cases:

1. a planned process that's still in progress
2. a planned process that has completed, and the plan was fully executed
3. a planned process that has completed, and the plan was not full executed

I think this is exhaustive, but if anyone has examples that fall outside these three then please let us know.

Today Bjoern presented these labels:

1. 'planned process'
2. 'successful planned process'
3. 'failed planned process'

There were objections to "successful" and we discussed several alternatives. I admit that "successful" can cause confusion, but one strength to keep in mind is that "successful" strongly contrasts with "failed".

**Comment by wdduncan** [comment]
See also issue #111

**Comment by wdduncan** [comment]
We need to add the axiom:
```
achieves_planned_objective some assay objective
```
to completed/successful planned processes

**Comment by bpeters42** [comment]
Sticking to the label discussion for the 'successful planned process': We had 'completed' instead of 'successful' in our original proposal, but it was pointed out that you can have a completed and failed planned process. Like an assay that was performed, and the controls show that it didn't work as planned. We switched to 'successful' based on that feedback. 

In the call today, it became clear that 'successful' triggers all kinds of associations beyond what is intended. So as an intermediate between 'completed' vs. 'successful', how about using

"completely executed planned process'

as the label.  Note that all we are talking about is the label; there were no objections in the call on the overall modeling scheme.

**Comment by wdduncan** [comment]
In the scheme today, all assays were under `completely executed planned process`. 

I was not aware of OBI's axiom for assays which states:
```
Equivalent to: achieves_planned_objective some assay objective
```
With this axiom, I assume COB would not allow for failed assays?

**Comment by jamesaoverton** [comment]
@wdduncan These slides go into more detail than we were able to this morning, but it looks like some things need to be updated based on the discussion today:

https://docs.google.com/presentation/d/1-tsRWLrBojH6bAUy0M0bBdYA8IQc7eDKVD_nStOMqSU/edit

**Comment by wdduncan** [comment]
Thanks for the pointer to the slides @jamesaoverton   

As you know, I do not think that concretizing plan specifications as realizables (i.e., `realizes (concretizes some plan specification)` makes much sense (ontologically).

**Comment by wdduncan** [comment]
Just to follow up:  
I understand what I think is the intent of `realizes (concretizes some plan specification)`: namely, the information directed (in some sense) how the plan was carried out.  

**If** BFO allowed for GDCs to have roles, it think a clearer representation would be something like:  
```
'plan specificification' 'has characteristic' some 'action directive role'
'planned process' realizes some 'action directive role'
```
In lieu of that, can we define some new relations to represent the relationship between a `plan specification` and a `planned process`? E.g.:  
```
'planned process' 'prescribed by' some 'plan specification' (I think common core does something like this)
or
'planned process' 'has directive input' some 'plan specification'
```
Hopefully, this will make more sense to end users, and will not require them to delve into concretization land.

**Comment by beckyjackson** [comment]
This is resolved.
