### ISSUE TITLE
Add biological entity/anatomical entity

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#112]
Per COB workshop:
Add class biological entity to cover organisms, gross anatomy, cellular, and subcellular anatomy.

**Comment by wdduncan** [comment]
See also #99 
This could replace 'anatomical entity' as a top-level entity.

**Comment by bpeters42** [comment]
My very personal opinion is that these kind of grouping terms do not add value to COB, as they reflect specific sub-field biases. I think we should strongly favor classes that can be logically defined in terms of scope. So 'anatomical entity' as 'part of' some organism is much less problematic in my mind that 'biological entity' where it gets very wishy-washy what the border is to 'chemical' or 'medical', or 'biochemical' or 'biomedical' or etc.

**Comment by nataled** [comment]
I don't have a strong opinion on this, but one could say that the value of such groupings lies in discoverability. That is, if someone was to navigate the ontology from the top down, such groupings could help find some specific class beneath it. Whether or not this particular case meets that mild standard is another question.

**Comment by cmungall** [comment]
Closed in favor #99
