### ISSUE TITLE
Move from CARO as the upper ontology for anatomical ontologies to COB

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#113]

**Comment by mellybelly** [comment]
I don't think it is being suggested to move AOs to COB but rather to align CARO and COB and have COB provide some basic interoperability.

**Comment by bpeters42** [comment]
+1 Melissa. That is exactly what we said yesterday (8/31). The whole purpose of COB is alignment, for anatomy and any other domain. We should close this ticket. @cmungall
