### ISSUE TITLE
Fix tsv2rdf.pl

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/COB#115]
@beckyjackson and I have not been able to run `util/tsv2rdf.pl`, and so we have not been able to update `cob-to-external.owl`. We get a `cob-to-external.ttl` file with prefixes and no content.

I used to know Perl and I've tried to hack at it, but without success.

We proposed #96 but @cmungall wants `cob-to-external.tsv` to remain in the current format. He says that format is either [SSSOM](https://github.com/OBOFoundry/SSSOM) (or close to it). If it's SSSOM then there should be a standard tool for this.

In any case, it's high priority for everybody to be able to update `cob-to-external.owl`.

@cmungall Can you please delegate this? Maybe to @matentzn?

**Comment by cmungall** [comment]
We believe this is fixed...

**Comment by jamesaoverton** [comment]
Working for me now. Thanks!

**Comment by matentzn** [comment]
I will close this and make a new ticket for moving to sssom-py
