### ISSUE TITLE
How to prioritize issues - can we use github 'reactions'? 

### ISSUE THREAD

**Issue by bpeters42** [OBOFoundry/COB#120]
We will always have more than enough things to do for COB. And we should prioritize to work on what is important to most users. So I would suggest to try the 'reaction' feature that is next to each github issue (click on the smiley face) to indicate if they give thumbs up or thumbs down on an issue (if they care about it) and no reaction (if they don't). 

This is not to replace discussion of what we should do, just to prioritize what we should talk about first. And that might include issues with massive thumbs down that we should close, or issues with half/half thumbs up or down that are clearly up in the air. But we should not spent time on issues that no one even cares to put their thumbs on :)

**Comment by matentzn** [comment]
I think this is a good idea! Maybe: 

| Code | Meaning |
| ----- | --------- |
| 🚀 | Important issue, lets prioritise |
| 😕 | Not sure I see the point of this right now, lets de-prioritise |
|  👍  | I agree with this suggestion | 
| 👎  | I disagree with this suggestion |

Maybe we only use the rocket 🚀  and not the 😕 face to not cause negative sentiment? 


Thumbs up for this is an important issues, thumbs down: lets not prioritise this now, :) smiling face I agree with the proposal,

**Comment by jamesaoverton** [comment]
For clarity: I think we agreed to use :rocket:, :+1:, and :-1:, as @matentzn proposed.

We can potentially write a script to count these reactions and generate a report.
