### ISSUE TITLE
Where to place "phenotypic quality" (PATO)

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/COB#124]
See #42 for context. 

Currently, we have `COB:0000001` (quality) directly equivalent with BFO:quality. Does this work for PATO:quality as well?

Thank you for your input @sbello @dosumis @seger @srobb1 @chris-grove @mah11 @nicolevasilevsky @Clare72 @ybradford (please tag all those pheno-heroes I have missed now).

**Comment by dosumis** [comment]
PATO term probably needs to map to COB:characteristic (?) see discussion in COB meeting on Sept 1st

**Comment by cmungall** [comment]
I didn't provide much of a summary at the time, so here is how this was resolved

COB:characteristic is declared equivalent to PATO:quality, cob-to-external is always the source of truth:

https://github.com/OBOFoundry/COB/commit/5c3e1ddd0797c5670b9be886ac11e37b2878aafd#diff-843144db558352aa8e49c08ee02d000e006ddd3b4e288314d8c12524118cb8f6R84

This does create an odd terminological slippage, to resolve this, either:

- PATO:quality should be renamed to "characteristic"
- BFO:quality should be renamed to something else

I am inclined to just note this terminological difference and move on, as I suspect neither community would be keen to change. 

(As a historic note, PATO adopted the term "quality" based on http://ontology.buffalo.edu/bfo/SQU.pdf, and the concept here more closely equates to what we now call characteristic, it was later that BFO restricted BFO:quality to apply only to continuants, but this is all noted elsewhere)

**Comment by wdduncan** [comment]
Unfortunately, the cob.owl makes this confusing. In COB, `realizable entity` is under `characteristic`.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/3186638/202827066-c6031ab6-e28c-4df9-89a9-aa9ecb0ea3e8.png">

But, in PATO, `realizable entity` is a sibling of `pato:quality`.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/3186638/202827131-1bf49292-94bb-4ab9-a565-50b27554df90.png">

**Comment by matentzn** [comment]
Dont concern yourself with "what PATO says" in terms of upper level alignment. It's likely accidental.

**Comment by wdduncan** [comment]
@matentzn I think this only makes things confusing. Depending on the ontology you look at, the following assertions are both true:
- realizable entity is a pato:quality (following the semantics expressed in cob-to-external)
- realizable entity is not a pato:qality (from pato)

I don't think pointing folks to the cob-to-external file is of much help to the larger ontology community who want to use cob, but also want the semantics between cob and other ontologies (e.g., pato) to be consistent.

**Comment by matentzn** [comment]
What I meant to say it, once agreement is reached here, at COB level, we will change PATO.

**Comment by wdduncan** [comment]
Ok.
