### ISSUE TITLE
Declare quality disjoint from realizable

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/COB#129]
Consistent with BFO

Note: this would currently render cob-base incoheret. See #121

**Comment by bpeters42** [comment]
We yesterday discussed how classes such as 'color' that are currently BFO:quality can also be considered realizables. So yes, this will make us consistent with BFO, but it might also mean we should avoid putting anything under 'bfo:quality'.

**Comment by cmungall** [comment]
We agree instead that COB will cede COB:quality. We don't necessarily disagree with the axiom but it's outside COB scope
