### ISSUE TITLE
Issue running `make`: No rule to make target `cob-edit.owl'

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/COB#174]
When I run `make`, I get the following error:

```
make: *** No rule to make target `cob-edit.owl', needed by `build/report.tsv'.  Stop.
```

Overall, it would be great to improve the docs for potential contributors on what they should run to go along with a PR

**Comment by matentzn** [comment]
Sorry about that, see #175

especially changes to docs/editors.md

**Comment by cthoyt** [comment]
Thanks, #175 will definitely close this
