### ISSUE TITLE
NTR: Gene Group

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/COB#186]
All entries in HGNC Gene Groups should be subclasses of Gene Group. This is a superclass of gene family, since it can include all sorts of classifications (based on parology, membership of their products in a complex, etc.)

Sequence ontology already provides an entry for gene groups:

https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0005855

However, since it falls under "biological region" it seems like it's more oriented towards stuff like operons, and not necessarily for arbitrary classifications

Related, there are several entries for gene families across ontologies with widely varying inheritance:
- NCIT https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C26004
- OGI (under material entity/object aggregate) https://www.ebi.ac.uk/ols/ontologies/ogi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOGI_0000081
- EDAM https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Ftopic_0623

It's probably the case that none of these are appropriate for mapping to COB

**Comment by cmungall** [comment]
The SO term is placed under region, and is intended for operons, BGCs, etc. It should probably be renamed.

HGNC gene groups are gene families.

The default OBO way of thinking (which I don't necessarily this is optimal) is that "gene" is a classes, instances of genes are spatiotemporal particulars (we don't need to relitigate GDC vs ME here, this was resolved in a previous COB workshop), and all HGNC gene IDs and gene family IDs denote subclasses of "gene". You can see PRO for how this is implemented in practice (metaclasses are comments).

For the more general issue see:

https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2454
