### ISSUE TITLE
problems with ontology IRIs

### ISSUE THREAD

**Issue by balhoff** [OBOFoundry/COB#197]
`http://purl.obolibrary.org/obo/cob.owl`
- [X] has unexpected version IRI: `http://purl.obolibrary.org/obo/cob/releases/2021-09-13/cob-native.owl`

`http://purl.obolibrary.org/obo/cob/cob-to-external.owl`
- [X] has no ontology IRI
- [X] has no version IRI

`http://purl.obolibrary.org/obo/cob/cob-base.owl`
- [X] has wrong ontology IRI: `http://purl.obolibrary.org/obo/cob.owl`
- [X] has wrong version IRI: `http://purl.obolibrary.org/obo/cob/releases/2021-09-13/cob-native.owl`
- [ ] contains label annotations about external terms (shouldn't be in base file)

- [X] The version IRI `http://purl.obolibrary.org/obo/cob/releases/2021-09-13/cob-native.owl` does not resolve.

**Comment by matentzn** [comment]
@balhoff 

I fixed all of these in #198, aside from "contains label annotations about external terms (shouldn't be in base file)". I don't have time to deal with that now, can you make a ticket that generally makes sure that COB base is a _true_ base?

> The version IRI `http://purl.obolibrary.org/obo/cob/releases/2021-09-13/cob-native.owl` does not resolve.

In fact, no COB version IRI was resolving, see:

https://github.com/OBOFoundry/purl.obolibrary.org/pull/837
