### ISSUE TITLE
Avoid use of "inverse(Property)" expression in class expressions in favour of providing an inverse relation

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/COB#229]
We rely a lot on ELK, and this kind of axiom, using complex property expressions in class expressions will result in incomplete reasoning:

```
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/COB_0000113">
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty>
                    <rdf:Description>
                        <owl:inverseOf rdf:resource="http://purl.obolibrary.org/obo/COB_0000087"/>
                    </rdf:Description>
                </owl:onProperty>
                <owl:allValuesFrom rdf:resource="http://purl.obolibrary.org/obo/COB_0000082"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:label xml:lang="en">plan</rdfs:label>
    </owl:Class>
```

I would like to propose to avoid use of "inverse(Property)" expression in class expressions in favour of providing a named inverse relation. Apart from the fact that we can actually use the expression for reasoning, it is much easier to read, and also better supported by ontology formats that are not OWL (OBO, obographs-json).

**Comment by bpeters42** [comment]
I believe the only reason we used 'inverse of' was that sometimes it was not-trival to come up with a label for the inverse property, and we wanted to move quickly. For the exact reasons Nico pointed out, we should move away from that.

**Comment by matentzn** [comment]
This is also causing OBO format conversions to break when people are importing COB directly..

**Comment by matentzn** [comment]
I not to hotfix some builds like

https://github.com/monarch-initiative/vertebrate-breed-ontology/commit/d509ecf57f094ef8638c74759d5f815294efc6e1

because the OBO error is so big that even `--check false` fails..

**Comment by matentzn** [comment]
I suggest to prioritise this as it is really a massive blocker for rolling out COB..

I spend another hour tracking this down now and it requires more than 5 years of ontology pipeline expertise to debug this..

**Comment by bpeters42** [comment]
Copying @sebastianduesing  - this should be straightforward to do, and it would be great to have it done in our pre-workshop release. If there is a problem finding a label for the inverse like I suspected above, we can start ugly with something like "inverse_of_other_relationship" - we can improve those labels later.

**Comment by sebastianduesing** [comment]
Done. No new labels needed.
