### ISSUE TITLE
environmental process

### ISSUE THREAD

**Issue by masciam** [OBOFoundry/COB#239]
I have a question about environmental process, since I did not seen the definition it is going to be intended as parent class of the 
http://purl.obolibrary.org/obo/ENVO_02500000
 wildfire and climate change can go both under environmental process?
i just need a clarification to better understand how to use the term.

**Comment by wdduncan** [comment]
Yes, such processes would go under `cob:environmental process`. In `envo`, the label is `environmental system process`, and `wildfire` http://purl.obolibrary.org/obo/ENVO_01000787 is a subclass of it.

**Comment by cmungall** [comment]
Nice to see a resolved issue!
