### ISSUE TITLE
COB_based_on annotation property without proper OBO ID

### ISSUE THREAD

**Issue by sebastianduesing** [OBOFoundry/COB#280]
(Edit: I mistakenly referred to this as a relation; it is an annotation property.)

The [COB_based_on](https://www.ebi.ac.uk/ols4/ontologies/cob/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCOB_based_on) annotation property does not have a proper OBO ID. I propose that we drop that property, as its five usages are applied in inconsistent ways:

- DRON:00000005 "drug product" COB_based_on DRON:00000005 (Edit to add: this is how this one appears when COB is imported into OBI. In COB, this links COB_0000088 to DRON:00000005. There's probably something analogous happening with the IAO:0000136 one.)
- COB:0000119 "evaluant role" COB_based_on "OBI:0000067"
- COB:0000120 "information representation" COB_based_on "http://purl.obolibrary.org/obo/IAO_0000015"
- IAO:0000136 "is about" COB_based_on "http://purl.obolibrary.org/obo/IAO_0000136"
- COB:0000121 "measurement datum" COB_based_on "http://purl.obolibrary.org/obo/IAO_0000109"

I'll make a PR shortly. If there concern about dropping this property, we could alternatively move the information in these statements to comments/editor notes on the relevant terms.

**Comment by bpeters42** [comment]
There was a reasonable good intent for this relation, namely that we indicate 'related' classes on which the COB term is 'based on' but is not exactly identical to. How are we going to capture this instead? using a 'comment' could be fine?
