### ISSUE TITLE
Add unit tests and .travis.yml

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/COB#31]

**Comment by cmungall** [comment]
Looks like we still don't have travis!

**Comment by cmungall** [comment]
![image](https://user-images.githubusercontent.com/50745/92013372-837dd200-ed02-11ea-86cc-d59531be7fa7.png)

**Comment by cmungall** [comment]
also need to set up gh actions

**Comment by jamesaoverton** [comment]
Travis has migrated from .org to .com. When I look at https://travis-ci.com/github/OBOFoundry/COB (I think) it's ready to go, and just needs a `.travis.yml`.

**Comment by wdduncan** [comment]
@cmungall Do we still need gh actions for this?
