### ISSUE TITLE
Information and information content entity as subclass of independent continuant

### ISSUE THREAD

**Issue by pfabry** [OBOFoundry/COB#59]
Hello,

First, thanks for releasing this ontology that will be really beneficial for integrating different ontologies together.

In addition, what are the reasons to subclass COB:information and its equivalent class IAO:information content entity under independent continuant instead of generically dependent continuant as it is actually in IAO?

Regards,

Paul

**Comment by jamesaoverton** [comment]
Thanks @pfabry! This applies to `cob-to-external.owl` and I think it's just a mistake. In `cob-edit.owl` we put 'information' at the top level.

**Comment by pfabry** [comment]
Thanks. The way I understand COB's use is that since many (most?) OBOfoundry ontologies are based on BFO, it's predominantly cob-to-external that needs to be imported to ensure interoperability?

**Comment by jamesaoverton** [comment]
There are some tricky bits and open questions, and we might not all be on the same page yet, but this is my view:

1. Most OBO ontologies would import `cob.owl` (built from `cob-edit.owl`) as their top-level.
2. If you need to connect to BFO-based non-OBO ontologies, you will import another file (`cob-to-bfo.owl`?) to fill out those links from COB to BFO.
3. The current `cob-to-external.owl` is for developers to explore links to BFO and many other OBO ontologies, and is not intended for end-users.

**Comment by pfabry** [comment]
Thanks for the clarification. I'm looking forward to an ICBO workshop on COB.

**Comment by wdduncan** [comment]
How strictly to we want to adhere to BFO when it comes to information? Recall that the same instance of GDCs can inhere in multiple entities at the same time. This makes for a very weird individual. Plus, then we have to consider if we want the `concretizes` relation, and if ICEs can be concretized as realizables, which I don't think makes much sense.

**Comment by cmungall** [comment]
Looks like this was fixed a while ago, so I am closing.
