### ISSUE TITLE
NTR: characteristic

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/COB#65]
synonym: property, attribute

this would be a parent of COB:quality and COB:realizable. I would go one step further and not bother with any distinction below 'characteristic' in COB.

in cob-to-external, pato:quality would be equivalent to cob:characteristic

**Comment by cmungall** [comment]
For related pato/ro ticket see: https://github.com/oborel/obo-relations/pull/284

**Comment by wdduncan** [comment]
I believe Barry is supposed to work on the equivalent axioms in BFO. E.g., a disease course/process that has the characteristic of being acute is supposed to be transformable into some set of BFO axioms.  
I do not know the status of this.

**Comment by bpeters42** [comment]
'characteristic' should go into COB, as that was the solution agreed upon in the last RO workshop to deal with the definition of 'inheres in' (which has incompatible range definitions in BFO vs. RO). If Barry works out axioms, great, but for now we should stick to what was a consensus decision at the last workshop.

**Comment by wdduncan** [comment]
@bpeters42 +1
