### ISSUE TITLE
immaterial entity - proposed definition

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/COB#75]
I propose the following **primitive** definition for immaterial entity:

a spatial extended entity that does not have mass

usage: material entities are located in immaterial entities

cc @cmungall

**Comment by alanruttenberg** [comment]
Why are you creating definitions for BFO-defined classes?

**Comment by wdduncan** [comment]
The upper level of COB does not have any definitions. If we assume that these are BFO classes, I fear we will got bogged down in overly metaphysical issues that COB is meant to side step (e.g., properties of processes). So, I am proposing alternative definitions.   
Mappings between BFO and COB are possible, this is a separate issue. If possible, I'd like to reserve this ticket for discussion of definitions.
