### ISSUE TITLE
Recent proposals for redefining BFO terms

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/COB#79]
It's very bad behavior to be redefining terms like this. It violates basic principles of reuse and semweb norms.

**Comment by wdduncan** [comment]
Although the COB terms have the same labels as BFO terms, the IRIs are different. We can of course change labels if they truly become separate entities than the corresponding BFO terms.  

My intent is to provide a more accessible upper level set of definitions that aren't constrained by contentious metaphysics regarding things such as processes having properties, generically dependent continuants, and the like.  After all, does anyone really agree on what it means for an ICE to be concretized?  

To be clear, I am not advocating the removal of BFO. It plays an important role in how best to relate metaphysics proper to computationally-based formal ontology.  However, there are already many OBO Foundry ontologies that don't strictly adhere to BFO principles. So, it seems to me at least that many ontologists are willing to part ways with BFO when they can't live up (or perhaps understand) the mandates of BFO.  Plus, many important ontologies (such OBI and CL) do try to adhere to BFO. So, it is necessary to continue maintaining and improving BFO.  

Also, I do not view COB as high-grade metaphysics. Rather, I see it as a more accessible upper level ontology for OBO Foundry developers that doesn't require understanding sophisticated and/or debatable notions about persistence and identity conditions.   

Mappings between COB should be made, and problematic mappings investigated.  

Hope this helps clarify my intention for posting the proposed definitions.  

cc @cmungall

**Comment by hoganwr** [comment]
I agree.  It's exceedingly objectionable.  I would refuse to use COB on
this basis alone in my own ontologies, and probably would stop reusing
COB-based ontologies.

**Comment by cmungall** [comment]
We are not providing new definitions for BFO classes.

We may want to provide additional user-friendly explanations, I assume this isn't controversial. Any proposed new such non-definitional annotation assertions should be done as PRs for comment by everyone.

But even this is not a priority at the moment, the focus of COB is on more specific classes not found in BFO

**Comment by alanruttenberg** [comment]
The issue names use the word "Definition".
The terms in question have had their IRIs changed.

**Comment by alanruttenberg** [comment]
@wdduncan what is the difference between the extensions of the not-bfo immaterial entity and the bfo material entity? As far as I can tell they mean the same. So giving a term a new IRI does not mean you aren't redefining them, except in the narrowest sense.

**Comment by alanruttenberg** [comment]
@cmungall Adding additional annotations is fine. Replacing the BFO terms with lookalike terms is not.

**Comment by alanruttenberg** [comment]
We can merge this issue with #81

**Comment by bpeters42** [comment]
Yes, please, let's discuss this in #81
