### ISSUE TITLE
Include pathway in COB

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/COB#98]
Budding this ticket from #39 (please read comments there before commenting here)

@RLWOHIO
> Should we consider biological pathway as a class above 'biological process'? Is current definition of biological process inclusive of pathways? A pathway contains multiple processes. In systems biology/omics, people normally refer to biological pathways such as those of KEGG/Reactome, not biological processes.

@addiehl 
> It strikes me that a pathway is really a subtype of a process, rather than the other way around. 

I agree with this

@RLWOHIO 
> I think it would be informative to include pathway in the obo core classes as it is such a prevalent concept.

I think this is a reasonable request

Previously I said
> We could include GO:0007165 signal transduction as an exemplar 

So we could include as exemplar or as class in its own right

**Comment by beckyjackson** [comment]
We have decided to not include pathway; the concept of pathway is fuzzy and we already have a term for "biological process". People can use precise classes from GO, such as "signal transduction".
